# Project metadata
name: 'demo_hackathon'
version: '1.0.0'
profile: 'demo_hackathon'

# File paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean targets
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Model configurations
models:
  demo_hackathon:
    raw_vault:
      +materialized: incremental
      +schema: raw_vault
      
    kpi:
      +materialized: table
      +schema: business_layer
